<script setup lang="ts">
import { computed, reactive, ref } from "vue";
import {
  ElButton,
  ElDescriptions,
  ElDescriptionsItem,
  ElDialog,
  ElMessage,
  ElMessageBox,
  ElPagination,
  ElTag,
} from "element-plus";
import OverviewHeader from "~/components/overview/OverviewHeader.vue";
import SmartTable from "~/components/table-edit/core/table/SmartTable.vue";
import BaseButton from "~/components/base/BaseButton.vue";
import { hrmsAdminService } from "~/api/hr_admin";
import type { PayrollRunDTO } from "~/api/hr_admin/payroll";
import type { ColumnConfig } from "~/components/types/tableEdit";

definePageMeta({ layout: "default" });

const payrollService = hrmsAdminService().payrollRun;

const loading = ref(false);
const actionLoading = ref<Record<string, boolean>>({});
const rows = ref<PayrollRunDTO[]>([]);

const pagination = reactive({
  page: 1,
  limit: 10,
  total: 0,
});

const detailDialogVisible = ref(false);
const detailLoading = ref(false);
const activeRun = ref<PayrollRunDTO | null>(null);

const tableColumns: ColumnConfig<PayrollRunDTO>[] = [
  {
    field: "id",
    label: "Run ID",
    minWidth: "190px",
    visible: true,
  },
  {
    field: "month",
    label: "Month",
    width: "130px",
    visible: true,
  },
  {
    field: "generated_by",
    label: "Generated By",
    minWidth: "180px",
    visible: true,
  },
  {
    field: "lifecycle",
    label: "Generated At",
    minWidth: "190px",
    visible: true,
    render: (row: PayrollRunDTO) => formatDateTime(row.lifecycle?.created_at),
  },
  {
    field: "status",
    label: "Status",
    width: "140px",
    visible: true,
    slotName: "status",
  },
  {
    field: "id",
    operation: true,
    label: "Actions",
    width: "280px",
    fixed: "right",
    visible: true,
    slotName: "operation",
  },
];

const totalByStatus = computed(() => {
  const result = {
    draft: 0,
    finalized: 0,
    paid: 0,
  };

  for (const row of rows.value) {
    const status = String(row.status || "").toLowerCase();
    if (status === "draft") result.draft += 1;
    if (status === "finalized") result.finalized += 1;
    if (status === "paid") result.paid += 1;
  }

  return result;
});

function formatDateTime(value?: string | null): string {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return date.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function statusLabel(status?: string | null): string {
  const map: Record<string, string> = {
    draft: "Draft",
    finalized: "Finalized",
    paid: "Paid",
  };
  return map[String(status || "").toLowerCase()] || "Unknown";
}

function statusTagType(status?: string | null): "warning" | "success" | "info" {
  const map: Record<string, "warning" | "success" | "info"> = {
    draft: "warning",
    finalized: "info",
    paid: "success",
  };

  return map[String(status || "").toLowerCase()] || "info";
}

function statusClass(status?: string | null): string {
  const map: Record<string, string> = {
    draft: "status-pill status-pill--draft",
    finalized: "status-pill status-pill--finalized",
    paid: "status-pill status-pill--paid",
  };
  return map[String(status || "").toLowerCase()] || "status-pill";
}

function canFinalize(row: PayrollRunDTO): boolean {
  return String(row.status || "").toLowerCase() === "draft";
}

function canMarkPaid(row: PayrollRunDTO): boolean {
  return String(row.status || "").toLowerCase() === "finalized";
}

async function fetchRuns(page = pagination.page, limit = pagination.limit) {
  loading.value = true;
  try {
    const response = await payrollService.listRuns({ page, limit });
    rows.value = response.items ?? [];
    pagination.total = response.total ?? rows.value.length;
    pagination.page = response.page ?? page;
    pagination.limit = response.page_size ?? limit;
  } catch {
    ElMessage.error("Failed to load payroll runs");
  } finally {
    loading.value = false;
  }
}

async function openDetail(row: PayrollRunDTO) {
  detailLoading.value = true;
  detailDialogVisible.value = true;
  try {
    activeRun.value = await payrollService.getRun(row.id);
  } catch {
    ElMessage.error("Failed to load payroll run detail");
    detailDialogVisible.value = false;
  } finally {
    detailLoading.value = false;
  }
}

async function finalizeRun(row: PayrollRunDTO) {
  try {
    await ElMessageBox.confirm(
      `Finalize payroll run ${row.month}?`,
      "Finalize Payroll Run",
      {
        type: "warning",
        confirmButtonText: "Finalize",
        cancelButtonText: "Cancel",
      },
    );
  } catch {
    return;
  }

  actionLoading.value[row.id] = true;
  try {
    await payrollService.finalizeRun(row.id);
    ElMessage.success("Payroll run finalized successfully");
    await fetchRuns(pagination.page, pagination.limit);
  } catch {
    ElMessage.error("Failed to finalize payroll run");
  } finally {
    actionLoading.value[row.id] = false;
  }
}

async function markRunPaid(row: PayrollRunDTO) {
  try {
    await ElMessageBox.confirm(
      `Mark payroll run ${row.month} as paid?`,
      "Mark Payroll Run Paid",
      {
        type: "warning",
        confirmButtonText: "Mark Paid",
        cancelButtonText: "Cancel",
      },
    );
  } catch {
    return;
  }

  actionLoading.value[row.id] = true;
  try {
    await payrollService.markRunPaid(row.id);
    ElMessage.success("Payroll run marked as paid");
    await fetchRuns(pagination.page, pagination.limit);
  } catch {
    ElMessage.error("Failed to mark payroll run as paid");
  } finally {
    actionLoading.value[row.id] = false;
  }
}

async function handlePageChange(page: number) {
  pagination.page = page;
  await fetchRuns(page, pagination.limit);
}

async function handlePageSizeChange(size: number) {
  pagination.limit = size;
  pagination.page = 1;
  await fetchRuns(1, size);
}

import { onMounted } from "vue";
onMounted(() => {
  fetchRuns(1, pagination.limit);
});
</script>

<template>
  <OverviewHeader
    :title="'Payroll Runs'"
    :description="'Manage payroll run lifecycle with finalize and mark paid actions'"
    :backPath="'/hr/payroll'"
  >
    <template #actions>
      <BaseButton
        plain
        :loading="loading"
        class="!border-[color:var(--color-primary)] !text-[color:var(--color-primary)] hover:!bg-[var(--color-primary-light-7)]"
        @click="fetchRuns(pagination.page, pagination.limit)"
      >
        Refresh
      </BaseButton>
    </template>
  </OverviewHeader>

  <div class="summary-strip">
    <el-tag effect="plain" class="summary-strip__tag">
      Total: {{ pagination.total }}
    </el-tag>
    <el-tag type="warning" effect="plain" class="summary-strip__tag">
      Draft: {{ totalByStatus.draft }}
    </el-tag>
    <el-tag type="info" effect="plain" class="summary-strip__tag">
      Finalized: {{ totalByStatus.finalized }}
    </el-tag>
    <el-tag type="success" effect="plain" class="summary-strip__tag">
      Paid: {{ totalByStatus.paid }}
    </el-tag>
  </div>

  <SmartTable
    :columns="tableColumns"
    :data="rows"
    :loading="loading"
    :total="pagination.total"
    :page="pagination.page"
    :page-size="pagination.limit"
    @page="handlePageChange"
    @page-size="handlePageSizeChange"
  >
    <template #status="{ row }">
      <ElTag
        :type="statusTagType(row.status)"
        effect="plain"
        round
        size="small"
        :class="statusClass(row.status)"
      >
        {{ statusLabel(row.status) }}
      </ElTag>
    </template>

    <template #operation="{ row }">
      <div class="action-group">
        <ElButton
          type="info"
          size="small"
          plain
          @click="openDetail(row as PayrollRunDTO)"
        >
          Open Detail
        </ElButton>

        <ElButton
          type="warning"
          size="small"
          plain
          :disabled="!canFinalize(row as PayrollRunDTO)"
          :loading="actionLoading[(row as PayrollRunDTO).id]"
          @click="finalizeRun(row as PayrollRunDTO)"
        >
          Finalize
        </ElButton>

        <ElButton
          type="success"
          size="small"
          plain
          :disabled="!canMarkPaid(row as PayrollRunDTO)"
          :loading="actionLoading[(row as PayrollRunDTO).id]"
          @click="markRunPaid(row as PayrollRunDTO)"
        >
          Mark Paid
        </ElButton>
      </div>
    </template>
  </SmartTable>

  <el-row v-if="pagination.total > 0" justify="end" class="m-4">
    <ElPagination
      :current-page="pagination.page"
      :page-size="pagination.limit"
      :total="pagination.total"
      :page-sizes="[10, 20, 50, 100]"
      layout="total, sizes, prev, pager, next, jumper"
      background
      @current-change="handlePageChange"
      @size-change="handlePageSizeChange"
    />
  </el-row>

  <ElDialog
    v-model="detailDialogVisible"
    title="Payroll Run Detail"
    width="560px"
  >
    <div v-loading="detailLoading">
      <ElDescriptions v-if="activeRun" :column="1" border>
        <ElDescriptionsItem label="Run ID">
          {{ activeRun.id }}
        </ElDescriptionsItem>
        <ElDescriptionsItem label="Month">
          {{ activeRun.month }}
        </ElDescriptionsItem>
        <ElDescriptionsItem label="Status">
          {{ statusLabel(activeRun.status) }}
        </ElDescriptionsItem>
        <ElDescriptionsItem label="Generated By">
          {{ activeRun.generated_by }}
        </ElDescriptionsItem>
        <ElDescriptionsItem label="Created At">
          {{ formatDateTime(activeRun.lifecycle?.created_at) }}
        </ElDescriptionsItem>
        <ElDescriptionsItem label="Updated At">
          {{ formatDateTime(activeRun.lifecycle?.updated_at) }}
        </ElDescriptionsItem>
      </ElDescriptions>
    </div>

    <template #footer>
      <ElButton @click="detailDialogVisible = false">Close</ElButton>
    </template>
  </ElDialog>
</template>

<style scoped>
.summary-strip {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
  margin-bottom: 14px;
}

.summary-strip__tag {
  font-weight: 600;
}

.status-pill {
  font-weight: 600;
  letter-spacing: 0.01em;
}

.status-pill--draft {
  border-color: #e6a23c;
  color: #b88230;
  background: #fff8eb;
}

.status-pill--finalized {
  border-color: #909399;
  color: #5d6066;
  background: #f4f4f5;
}

.status-pill--paid {
  border-color: #67c23a;
  color: #3b8f1d;
  background: #f1faec;
}

.action-group {
  display: inline-flex;
  align-items: center;
  gap: 6px;
}
</style>
