class NotifType:
    CLASS_ASSIGNMENT = "CLASS_ASSIGNMENT"
    CLASS_UNASSIGNED = "CLASS_UNASSIGNED"
    CLASS_ENROLLED = "CLASS_ENROLLED"
    CLASS_REMOVED = "CLASS_REMOVED"

    SCHEDULE_ASSIGNED = "SCHEDULE_ASSIGNED"
    SCHEDULE_UPDATED = "SCHEDULE_UPDATED"

    GRADE_PUBLISHED = "GRADE_PUBLISHED"

    ANNOUNCEMENT = "ANNOUNCEMENT"

    HRMS_LEAVE_SUBMITTED = "HRMS_LEAVE_SUBMITTED"
    HRMS_LEAVE_APPROVED = "HRMS_LEAVE_APPROVED"
    HRMS_LEAVE_REJECTED = "HRMS_LEAVE_REJECTED"
    HRMS_LEAVE_CANCELLED = "HRMS_LEAVE_CANCELLED"

    HRMS_OVERTIME_SUBMITTED = "HRMS_OVERTIME_SUBMITTED"
    HRMS_OVERTIME_APPROVED = "HRMS_OVERTIME_APPROVED"
    HRMS_OVERTIME_REJECTED = "HRMS_OVERTIME_REJECTED"
    HRMS_OVERTIME_CANCELLED = "HRMS_OVERTIME_CANCELLED"

    HRMS_PAYROLL_GENERATED = "HRMS_PAYROLL_GENERATED"
    HRMS_PAYROLL_FINALIZED = "HRMS_PAYROLL_FINALIZED"
    HRMS_PAYROLL_MARKED_PAID = "HRMS_PAYROLL_MARKED_PAID"
    HRMS_PAYSLIP_READY = "HRMS_PAYSLIP_READY"

    HRMS_ATTENDANCE_WRONG_LOCATION_APPROVED = "HRMS_ATTENDANCE_WRONG_LOCATION_APPROVED"
    HRMS_ATTENDANCE_WRONG_LOCATION_REJECTED = "HRMS_ATTENDANCE_WRONG_LOCATION_REJECTED"
    HRMS_ATTENDANCE_EARLY_LEAVE_APPROVED = "HRMS_ATTENDANCE_EARLY_LEAVE_APPROVED"
    HRMS_ATTENDANCE_EARLY_LEAVE_REJECTED = "HRMS_ATTENDANCE_EARLY_LEAVE_REJECTED"

    @classmethod
    def all(cls) -> set[str]:
        return {
            cls.CLASS_ASSIGNMENT,
            cls.CLASS_UNASSIGNED,
            cls.CLASS_ENROLLED,
            cls.CLASS_REMOVED,
            cls.SCHEDULE_ASSIGNED,
            cls.SCHEDULE_UPDATED,
            cls.GRADE_PUBLISHED,
            cls.ANNOUNCEMENT,
            cls.HRMS_LEAVE_SUBMITTED,
            cls.HRMS_LEAVE_APPROVED,
            cls.HRMS_LEAVE_REJECTED,
            cls.HRMS_LEAVE_CANCELLED,
            cls.HRMS_OVERTIME_SUBMITTED,
            cls.HRMS_OVERTIME_APPROVED,
            cls.HRMS_OVERTIME_REJECTED,
            cls.HRMS_OVERTIME_CANCELLED,
            cls.HRMS_PAYROLL_GENERATED,
            cls.HRMS_PAYROLL_FINALIZED,
            cls.HRMS_PAYROLL_MARKED_PAID,
            cls.HRMS_PAYSLIP_READY,
            cls.HRMS_ATTENDANCE_WRONG_LOCATION_APPROVED,
            cls.HRMS_ATTENDANCE_WRONG_LOCATION_REJECTED,
            cls.HRMS_ATTENDANCE_EARLY_LEAVE_APPROVED,
            cls.HRMS_ATTENDANCE_EARLY_LEAVE_REJECTED,
        }
