class NotifType:
    CLASS_ASSIGNMENT = "CLASS_ASSIGNMENT"
    CLASS_UNASSIGNED = "CLASS_UNASSIGNED"
    CLASS_ENROLLED = "CLASS_ENROLLED"
    CLASS_REMOVED = "CLASS_REMOVED"

    SCHEDULE_ASSIGNED = "SCHEDULE_ASSIGNED"
    SCHEDULE_UPDATED = "SCHEDULE_UPDATED"

    GRADE_PUBLISHED = "GRADE_PUBLISHED"

    ANNOUNCEMENT = "ANNOUNCEMENT"

    @classmethod
    def all(cls) -> set[str]:
        return {
            cls.CLASS_ASSIGNMENT,
            cls.CLASS_UNASSIGNED,
            cls.CLASS_ENROLLED,
            cls.CLASS_REMOVED,
            cls.SCHEDULE_ASSIGNED,
            cls.SCHEDULE_UPDATED,
            cls.GRADE_PUBLISHED,
            cls.ANNOUNCEMENT,
        }