export const allStudents = ref([
  "Ethan Clark",
  "Ava Rodriguez",
  "Noah Lewis",
  "Sophia Lee",
  "James Wilson",
  "Amelia Davis",
  "Mason Hall",
  "Ella Young",
  "Charlotte Lewis",
  "Logan Hall",
  "Grace Adams",
  "Isabella Martinez",
  "Jacob Walker",
  "Aiden Allen",
  "Lily Carter",
  "Jack Murphy",
]);

export const classes = ref<any[]>([
  {
    id: "1",
    name: "Math 101",
    grade: 1,
    max_students: 30,
    status: "active",
    homeroom_teacher: "Alice Johnson",
    students: [...allStudents.value],
    subjects: ["Algebra", "Geometry"],
    created_by: "Admin",
    created_at: "2025-09-20T10:00:00",
    updated_at: "2025-09-22T12:00:00",
  },
  {
    id: "2",
    name: "English 201",
    grade: 2,
    max_students: 25,
    status: "active",
    homeroom_teacher: "Robert Green",
    students: [...allStudents.value],
    subjects: ["Literature", "Writing"],
    created_by: "Admin",
    created_at: "2025-09-21T09:30:00",
    updated_at: "2025-09-23T11:00:00",
  },
  {
    id: "3",
    name: "Physics 301",
    grade: 3,
    max_students: 28,
    status: "inactive",
    homeroom_teacher: "Dr. Henry Wu",
    students: [...allStudents.value],
    subjects: ["Mechanics", "Optics"],
    created_by: "Admin",
    created_at: "2025-09-18T08:15:00",
    updated_at: "2025-09-22T10:45:00",
  },
  {
    id: "4",
    name: "History 101",
    grade: 1,
    max_students: 30,
    status: "active",
    homeroom_teacher: "Mary Collins",
    students: [...allStudents.value],
    subjects: ["World History", "Civics"],
    created_by: "Admin",
    created_at: "2025-09-19T14:00:00",
    updated_at: "2025-09-21T16:30:00",
  },
  {
    id: "5",
    name: "Chemistry 201",
    grade: 2,
    max_students: 32,
    status: "active",
    homeroom_teacher: "Dr. Angela Carter",
    students: [...allStudents.value],
    subjects: ["Organic Chemistry", "Inorganic Chemistry"],
    created_by: "Admin",
    created_at: "2025-09-20T12:45:00",
    updated_at: "2025-09-23T09:15:00",
  },
  {
    id: "6",
    name: "Biology 301",
    grade: 3,
    max_students: 30,
    status: "inactive",
    homeroom_teacher: "Dr. Susan Miller",
    students: [...allStudents.value],
    subjects: ["Botany", "Zoology"],
    created_by: "Admin",
    created_at: "2025-09-17T13:20:00",
    updated_at: "2025-09-20T15:50:00",
  },
  {
    id: "7",
    name: "Computer Science 101",
    grade: 1,
    max_students: 30,
    status: "active",
    homeroom_teacher: "Mr. Kevin Turner",
    students: [...allStudents.value],
    subjects: ["Programming", "Algorithms"],
    created_by: "Admin",
    created_at: "2025-09-21T11:10:00",
    updated_at: "2025-09-24T13:25:00",
  },
  {
    id: "8",
    name: "Art 101",
    grade: 1,
    max_students: 20,
    status: "active",
    homeroom_teacher: "Ms. Linda Evans",
    students: [...allStudents.value],
    subjects: ["Painting", "Sculpture"],
    created_by: "Admin",
    created_at: "2025-09-22T10:05:00",
    updated_at: "2025-09-25T12:40:00",
  },
  {
    id: "9",
    name: "Music 201",
    grade: 2,
    max_students: 18,
    status: "active",
    homeroom_teacher: "Mr. Daniel Roberts",
    students: [...allStudents.value],
    subjects: ["Choir", "Instrumental"],
    created_by: "Admin",
    created_at: "2025-09-20T09:55:00",
    updated_at: "2025-09-22T11:30:00",
  },
  {
    id: "10",
    name: "Physical Education 101",
    grade: 1,
    max_students: 25,
    status: "active",
    homeroom_teacher: "Coach John Smith",
    students: [...allStudents.value],
    subjects: ["Soccer", "Basketball", "Swimming"],
    created_by: "Admin",
    created_at: "2025-09-19T08:30:00",
    updated_at: "2025-09-21T10:45:00",
  },
]);
