from .common import BaseDTO
from .iam import *
from .staff import *
from .student import *
from .subject import *
from .classes import *
from .schedule import *
from .dashboard import *
from .composites import *