<script setup lang="ts">
import { computed, reactive, ref } from "vue";
import { ElPagination, ElTag } from "element-plus";
import OverviewHeader from "~/components/overview/OverviewHeader.vue";
import SmartTable from "~/components/table-edit/core/table/SmartTable.vue";
import BaseButton from "~/components/base/BaseButton.vue";
import { hrmsAdminService } from "~/api/hr_admin";
import type { ColumnConfig } from "~/components/types/tableEdit";
import type { PayrollRunDTO, PayslipDTO } from "~/api/hr_admin/payroll";
import { ROUTES } from "~/constants/routes";
import { displayRelation } from "~/api/hr_admin/shared/displayRelation";

definePageMeta({ layout: "default" });

const router = useRouter();
const payrollService = hrmsAdminService().payrollRun;

const runsLoading = ref(false);
const payslipsLoading = ref(false);

const runRows = ref<PayrollRunDTO[]>([]);
const payslipRows = ref<PayslipDTO[]>([]);

const runPagination = reactive({
  page: 1,
  limit: 10,
  total: 0,
});

const payslipPagination = reactive({
  page: 1,
  limit: 10,
  total: 0,
});

const runColumns: ColumnConfig<PayrollRunDTO>[] = [
  {
    field: "payroll_run_label",
    label: "Payroll Run",
    minWidth: "180px",
    visible: true,
    render: (row: PayrollRunDTO) =>
      displayRelation(row.payroll_run_label, row.payroll_month || row.month),
  },
  {
    field: "month",
    label: "Month",
    width: "110px",
    visible: true,
    render: (row: PayrollRunDTO) =>
      displayRelation(row.payroll_month, row.month),
  },
  {
    field: "generated_by",
    label: "Generated By",
    minWidth: "170px",
    visible: true,
    render: (row: PayrollRunDTO) =>
      displayRelation(row.generated_by_name, row.generated_by),
  },
  {
    field: "status",
    label: "Status",
    width: "130px",
    visible: true,
    slotName: "run_status",
  },
  {
    field: "lifecycle",
    label: "Created At",
    minWidth: "180px",
    visible: true,
    render: (row: PayrollRunDTO) => formatDateTime(row.lifecycle?.created_at),
  },
];

const payslipColumns: ColumnConfig<PayslipDTO>[] = [
  {
    field: "payroll_run_id",
    label: "Payroll Run",
    minWidth: "180px",
    visible: true,
    render: (row: PayslipDTO) =>
      displayRelation(
        row.payroll_run_label,
        row.payroll_month || row.month || row.payroll_run_id,
      ),
  },
  {
    field: "employee_id",
    label: "Employee",
    minWidth: "130px",
    visible: true,
    render: (row: PayslipDTO) =>
      displayRelation(row.employee_name, row.employee_id),
  },
  {
    field: "month",
    label: "Month",
    width: "110px",
    visible: true,
    render: (row: PayslipDTO) =>
      displayRelation(row.payroll_month, row.month),
  },
  {
    field: "net_salary",
    label: "Net Salary",
    width: "130px",
    visible: true,
    render: (row: PayslipDTO) => formatMoney(row.net_salary),
  },
  {
    field: "status",
    label: "Status",
    width: "120px",
    visible: true,
    slotName: "payslip_status",
  },
  {
    field: "lifecycle",
    label: "Created At",
    minWidth: "180px",
    visible: true,
    render: (row: PayslipDTO) => formatDateTime(row.lifecycle?.created_at),
  },
];

const runSummary = computed(() => {
  const result = {
    draft: 0,
    finalized: 0,
    paid: 0,
  };

  for (const row of runRows.value) {
    const status = String(row.status || "").toLowerCase();
    if (status === "draft") result.draft += 1;
    if (status === "finalized") result.finalized += 1;
    if (status === "paid") result.paid += 1;
  }

  return result;
});

const pageNetSalary = computed(() => {
  return payslipRows.value.reduce(
    (sum, row) => sum + Number(row.net_salary || 0),
    0,
  );
});

function formatDateTime(value?: string | null): string {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return date.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function formatMoney(value?: number | null): string {
  const amount = Number(value ?? 0);
  if (!Number.isFinite(amount)) return "-";
  return amount.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function runStatusType(status?: string | null): "warning" | "success" | "info" {
  const map: Record<string, "warning" | "success" | "info"> = {
    draft: "warning",
    finalized: "info",
    paid: "success",
  };
  return map[String(status || "").toLowerCase()] || "info";
}

function payslipStatusType(
  status?: string | null,
): "warning" | "success" | "info" {
  const map: Record<string, "warning" | "success" | "info"> = {
    generated: "warning",
    paid: "success",
  };
  return map[String(status || "").toLowerCase()] || "info";
}

function runStatusClass(status?: string | null): string {
  const map: Record<string, string> = {
    draft: "status-pill status-pill--draft",
    finalized: "status-pill status-pill--finalized",
    paid: "status-pill status-pill--paid",
  };
  return map[String(status || "").toLowerCase()] || "status-pill";
}

function payslipStatusClass(status?: string | null): string {
  const map: Record<string, string> = {
    generated: "status-pill status-pill--draft",
    paid: "status-pill status-pill--paid",
  };
  return map[String(status || "").toLowerCase()] || "status-pill";
}

async function fetchRuns(
  page = runPagination.page,
  limit = runPagination.limit,
) {
  runsLoading.value = true;
  try {
    const response = await payrollService.listRuns({ page, limit });
    runRows.value = response.items ?? [];
    runPagination.total = response.total ?? runRows.value.length;
    runPagination.page = response.page ?? page;
    runPagination.limit = response.page_size ?? limit;
  } finally {
    runsLoading.value = false;
  }
}

async function fetchPayslips(
  page = payslipPagination.page,
  limit = payslipPagination.limit,
) {
  payslipsLoading.value = true;
  try {
    const response = await payrollService.listPayslips({ page, limit });
    payslipRows.value = response.items ?? [];
    payslipPagination.total = response.total ?? payslipRows.value.length;
    payslipPagination.page = response.page ?? page;
    payslipPagination.limit = response.page_size ?? limit;
  } finally {
    payslipsLoading.value = false;
  }
}

async function refreshAll() {
  await Promise.all([
    fetchRuns(runPagination.page, runPagination.limit),
    fetchPayslips(payslipPagination.page, payslipPagination.limit),
  ]);
}

async function handleRunPageChange(page: number) {
  runPagination.page = page;
  await fetchRuns(page, runPagination.limit);
}

async function handleRunPageSizeChange(size: number) {
  runPagination.limit = size;
  runPagination.page = 1;
  await fetchRuns(1, size);
}

async function handlePayslipPageChange(page: number) {
  payslipPagination.page = page;
  await fetchPayslips(page, payslipPagination.limit);
}

async function handlePayslipPageSizeChange(size: number) {
  payslipPagination.limit = size;
  payslipPagination.page = 1;
  await fetchPayslips(1, size);
}

import { onMounted } from "vue";
onMounted(() => {
  refreshAll();
});
</script>

<template>
  <OverviewHeader
    :title="'Payroll History'"
    :description="'Combined history view of payroll runs and payslips'"
    :backPath="'/hr/payroll'"
  >
    <template #actions>
      <BaseButton
        plain
        :loading="runsLoading || payslipsLoading"
        class="!border-[color:var(--color-primary)] !text-[color:var(--color-primary)] hover:!bg-[var(--color-primary-light-7)]"
        @click="refreshAll"
      >
        Refresh
      </BaseButton>
      <BaseButton plain @click="router.push(ROUTES.HR_ADMIN.PAYROLL_RUNS)">
        Open Runs
      </BaseButton>
      <BaseButton plain @click="router.push(ROUTES.HR_ADMIN.PAYSLIPS)">
        Open Payslips
      </BaseButton>
    </template>
  </OverviewHeader>

  <div class="summary-strip">
    <el-tag effect="plain" class="summary-strip__tag">
      Runs: {{ runPagination.total }}
    </el-tag>
    <el-tag type="warning" effect="plain" class="summary-strip__tag">
      Draft: {{ runSummary.draft }}
    </el-tag>
    <el-tag type="info" effect="plain" class="summary-strip__tag">
      Finalized: {{ runSummary.finalized }}
    </el-tag>
    <el-tag type="success" effect="plain" class="summary-strip__tag">
      Paid: {{ runSummary.paid }}
    </el-tag>
    <el-tag type="success" effect="plain" class="summary-strip__tag">
      Payslip Page Net: {{ formatMoney(pageNetSalary) }}
    </el-tag>
  </div>

  <h3 class="section-title">Payroll Runs History</h3>
  <SmartTable
    :columns="runColumns"
    :data="runRows"
    :loading="runsLoading"
    :total="runPagination.total"
    :page="runPagination.page"
    :page-size="runPagination.limit"
    @page="handleRunPageChange"
    @page-size="handleRunPageSizeChange"
  >
    <template #run_status="{ row }">
      <ElTag
        :type="runStatusType(row.status)"
        effect="plain"
        round
        size="small"
        :class="runStatusClass(row.status)"
      >
        {{ String(row.status || "-").toUpperCase() }}
      </ElTag>
    </template>
  </SmartTable>

  <el-row v-if="runPagination.total > 0" justify="end" class="m-4">
    <ElPagination
      :current-page="runPagination.page"
      :page-size="runPagination.limit"
      :total="runPagination.total"
      :page-sizes="[10, 20, 50, 100]"
      layout="total, sizes, prev, pager, next, jumper"
      background
      @current-change="handleRunPageChange"
      @size-change="handleRunPageSizeChange"
    />
  </el-row>

  <h3 class="section-title section-title--payslips">Payslips History</h3>
  <SmartTable
    :columns="payslipColumns"
    :data="payslipRows"
    :loading="payslipsLoading"
    :total="payslipPagination.total"
    :page="payslipPagination.page"
    :page-size="payslipPagination.limit"
    @page="handlePayslipPageChange"
    @page-size="handlePayslipPageSizeChange"
  >
    <template #payslip_status="{ row }">
      <ElTag
        :type="payslipStatusType(row.status)"
        effect="plain"
        round
        size="small"
        :class="payslipStatusClass(row.status)"
      >
        {{ String(row.status || "-").toUpperCase() }}
      </ElTag>
    </template>
  </SmartTable>

  <el-row v-if="payslipPagination.total > 0" justify="end" class="m-4">
    <ElPagination
      :current-page="payslipPagination.page"
      :page-size="payslipPagination.limit"
      :total="payslipPagination.total"
      :page-sizes="[10, 20, 50, 100]"
      layout="total, sizes, prev, pager, next, jumper"
      background
      @current-change="handlePayslipPageChange"
      @size-change="handlePayslipPageSizeChange"
    />
  </el-row>
</template>

<style scoped>
.summary-strip {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
  margin-bottom: 14px;
}

.summary-strip__tag {
  font-weight: 600;
}

.section-title {
  margin: 10px 0 10px;
  font-size: 16px;
  font-weight: 700;
  color: #303133;
}

.section-title--payslips {
  margin-top: 20px;
}

.status-pill {
  font-weight: 600;
  letter-spacing: 0.01em;
}

.status-pill--draft {
  border-color: #e6a23c;
  color: #b88230;
  background: #fff8eb;
}

.status-pill--finalized {
  border-color: #909399;
  color: #5d6066;
  background: #f4f4f5;
}

.status-pill--paid {
  border-color: #67c23a;
  color: #3b8f1d;
  background: #f1faec;
}
</style>
