from typing import Protocol, Optional
from bson import ObjectId


class StudentMembershipPort(Protocol):
    def list_student_ids_in_class(self, class_id: ObjectId, *, session=None) -> set[ObjectId]: ...

    def exists(self, student_id: ObjectId, *, session=None) -> bool: ...
    def get_current_class_id(self, student_id: ObjectId, *, session=None) -> Optional[ObjectId]: ...

    def try_join_class(self, student_id: ObjectId, class_id: ObjectId, *, session=None) -> bool: ...
    def try_leave_class(self, student_id: ObjectId, class_id: ObjectId, *, session=None) -> bool: ...
    def revert_join(self, student_id: ObjectId, class_id: ObjectId, *, session=None) -> None: ...